name: Lint&Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v4

      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies ⚙️
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Log Python environment ✏️
        run: |
          pip freeze

      - name: black ◼️
        run: black --check .

      - name: flake8 ❄️
        run: flake8 .

      - name: mypy 🧐
        run: mypy

      - name: check-manifest 📰
        run: check-manifest

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install configurable-http-proxy
        run: |
          npm install -g configurable-http-proxy
          npm list

      - name: pytest tests 👓
        run: python -m pytest -v
